Make remote backup script work

diff --git a/backup/backup_remote b/backup/backup_remote
--- a/backup/backup_remote
+++ b/backup/backup_remote
@@ -4,50 +4,75 @@
 ## db data, redis data, uploaded files, prerun files and results
 set -eE
 
-help() {
-    # Display Help
-    echo "Backup naomi volumes and keys to a remote server"
-    echo
-    echo "Usage:"
-    echo "  backup_remote <target>"
-    echo
-    echo "Args:"
-    echo "  target   Remote location and path to write backup to in the form [user@]host:[path]"
-    echo
-    echo "Options:"
-    echo "  -h       Show help."
-    echo
-}
+USAGE="Backup naomi volumes and keys to a remote server
+Usage: $(basename "$0") [-h] <target>
+Options:
+    -h     Show this help text
+Args:
+    target Remote location and path to write backup to in the form [user@]host:[path]"
 
-while getopts ":h" option; do
-    case $option in
-    h) # display Help
-        help
-        exit
+if [[ -z "$@" ]]; then
+    echo "$USAGE"
+    exit 1
+fi
+OPTIONS=$(getopt -o h -- "$@")
+
+eval set -- "$OPTIONS"
+while true; do
+    case "$1" in
+    -h)
+        echo "$USAGE"
+        exit 0
+        ;;
+    --)
+        shift
+        break
         ;;
     esac
 done
 
+TARGET=$1
+IFS=':' read -ra PARTS <<<"$TARGET"
+if [ ${#PARTS[@]} -ne 2 ]; then
+    echo "Target must be in form [user@]host:[path]"
+    exit 1
+fi
+SERVER=${PARTS[0]}
+BACKUP_DIR=${PARTS[1]}
+
+## Verify that we can ssh onto server
+RESULT=0
+ssh -q -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=5 $SERVER 'exit 0' || RESULT=$?
+if [ $RESULT -ne 0 ]; then
+    echo "Cannot ssh onto server $SERVER check you have access"
+    exit 1
+fi
+
+if ! $(ssh $SERVER "[ -d $BACKUP_DIR ]"); then
+    echo "Path $BACKUP_DIR does not exist on $SERVER"
+    exit 1
+fi
+
 NOW=$(date +'%Y_%d_%m-%H_%M_%S')
-BACKUP_PATH="$SCRIPT_DIR/$NOW.tar"
-BACKUP_WORKING_DIR="$SCRIPT_DIR/working"
-mkdir $BACKUP_WORKING_DIR
+BACKUP_PATH="$BACKUP_DIR/$NOW.tar"
+BACKUP_WORKING_DIR="$BACKUP_DIR/working"
+ssh $SERVER "mkdir $BACKUP_WORKING_DIR"
 
 clean_up() {
     local lineno=$1
     local msg=$2
     echo "Backup failed at $lineno: $msg"
-    rm -rf $BACKUP_WORKING_DIR
+    ssh $SERVER "rm -rf $BACKUP_WORKING_DIR"
     exit 1
 }
 trap 'clean_up ${LINENO} "$BASH_COMMAND"' ERR
 
-docker exec hint_db pg_dumpall -U postgres >$BACKUP_WORKING_DIR/db_dump.sql
-docker run --rm --volumes-from hint_redis -v $BACKUP_WORKING_DIR:/backup busybox tar -cf /backup/redis_backup.tar -C /data .
-docker run --rm --volumes-from hint_hintr -v $BACKUP_WORKING_DIR:/backup busybox tar -cf /backup/prerun_backup.tar -C /prerun .
-docker run --rm --volumes-from hint_hintr -v $BACKUP_WORKING_DIR:/backup busybox tar -cf /backup/results_backup.tar -C /results .
-docker run --rm --volumes-from hint_hintr -v $BACKUP_WORKING_DIR:/backup busybox tar -cf /backup/uploads_backup.tar -C /uploads .
-find $BACKUP_WORKING_DIR -type f \( -not -name "checklist.chk" \) -exec md5sum "{}" + >$BACKUP_WORKING_DIR/checklist.chk
+docker exec hint_db pg_dumpall -U postgres | ssh $SERVER "cat > $BACKUP_WORKING_DIR/db_dump.sql"
+docker run --rm --volumes-from hint_redis busybox tar cvzf - -C /data . | ssh $SERVER "cat > $BACKUP_WORKING_DIR/redis_backup.tar"
+docker run --rm --volumes-from hint_hintr busybox tar cvzf - -C /prerun . | ssh $SERVER "cat > $BACKUP_WORKING_DIR/prerun_backup.tar"
+docker run --rm --volumes-from hint_hintr busybox tar cvzf - -C /results . | ssh $SERVER "cat > $BACKUP_WORKING_DIR/results_backup.tar"
+docker run --rm --volumes-from hint_hintr busybox tar cvzf - -C /uploads . | ssh $SERVER "cat > $BACKUP_WORKING_DIR/uploads_backup.tar"
+ssh $SERVER "find $BACKUP_WORKING_DIR -type f \( -not -name \"checklist.chk\" \) -exec md5sum \"{}\" + >$BACKUP_WORKING_DIR/checklist.chk"
 
 VAULT_PATH="secret/hint/$HOSTNAME/cipher"
 VAULT_ADDR="https://vault.dide.ic.ac.uk:8200"
@@ -63,9 +88,9 @@ if [[ $REPLY =~ ^[Yy]$ ]]; then
     PRIVATE_KEY=$(docker run --rm --volumes-from hint_hint busybox cat /etc/hint/token_key/private_key.der | base64 --wrap=0)
     echo "Writing to $VAULT_PATH"
     vault write -address=$VAULT_ADDR $VAULT_PATH public=$PUBLIC_KEY private=$PRIVATE_KEY
-    echo "$VAULT_PATH" >$BACKUP_WORKING_DIR/cipher_path
+    echo "$VAULT_PATH" | ssh $SERVER "cat > $BACKUP_WORKING_DIR/cipher_path"
 fi
 
-tar -cf $BACKUP_PATH -C $BACKUP_WORKING_DIR .
-echo "Backup complete, saved at $BACKUP_PATH"
-rm -rf $BACKUP_WORKING_DIR
+ssh $SERVER "tar -cf $BACKUP_PATH -C $BACKUP_WORKING_DIR ."
+echo "Backup complete, saved at $SERVER:$BACKUP_PATH"
+ssh $SERVER "rm -rf $BACKUP_WORKING_DIR"
